---
title: "hw-01-s2479602"
author: "katy bannister S2479602"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}    
knitr::opts_chunk$set(out.width = "100%")
```


------------------------------------------------------------------------------

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse)
library(lubridate)

edibnb <- read_csv("data/edibnb.csv")
council <- read_csv("data/council_assessments.csv")


```

------------------------------------------------------------------------------


## EXERCISE 1

```{r hw1-ex1}
print("Count of missing values by column wise") 
sapply(edibnb, function(x) 
sum(is.na(x)))

library(dplyr)

```



1. price, neighbourhoods, bathrooms, bedrooms, beds, review scores rating
2. 860170


------------------------------------------------------------------------------

## EXERCISE 2

```{r hw1-ex2}


```


_Remove this text, and add your answer for Exercise 2 here._


------------------------------------------------------------------------------

## EXERCISE 3

```{r hw1-ex3}
# remove this comment and add the code for Exercise 3 here

```


_Remove this text, and add your answer for Exercise 3 here._



------------------------------------------------------------------------------

## EXERCISE 4

```{r hw1-ex4}
# remove this comment and add the code for Exercise 4 here

```


_Remove this text, and add your answer for Exercise 4 here._


------------------------------------------------------------------------------
